image: node:10-alpine

stages:
  - lint
  - test
  - release

before_script:
  - npm install

cache:
  paths:
    - node_modules/

lint:
  stage: lint
  script:
    - npm run lint
  tags:
    - dind

test:
  stage: test
  script:
    - npm run test
  tags:
    - dind

release:
  stage: release
  only:
    - tags
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish
  tags:
    - dind
