image: node:10-alpine

variables:
  GIT_STRATEGY: clone
  NPM_TOKEN: $NPM_TOKEN

stages:
  - lint
  - test
  - release

before_script:
  - npm install

cache:
  paths:
    - node_modules/

lint:
  stage: lint
  script:
    - npm run lint
  tags:
    - dind

test:
  stage: test
  script:
    - npm run test
  tags:
    - dind

release:
  stage: release
  only:
    - tags
  script:
    - npm --version
    - echo $NPM_TOKEN
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - if [ ${NPM_TOKEN:0:1} = "v" ]; then npm publish fi
  tags:
    - dind
